### ISSUE TITLE
Quality Icon changes into text in advertise macro

### ISSUE THREAD

**Issue by chriser-** [NumyAddon/MacroToolkit#13]
When I want to link an item in a macro, the Quality Icon changes into text as soon as I write for example /2 in front of it
![image](https://user-images.githubusercontent.com/5705155/206875624-69cf154d-1356-49f0-8448-e90d47a78818.png)
It looks fine without /2
![image](https://user-images.githubusercontent.com/5705155/206875639-f3018227-2c7d-4d28-82a9-005fa4765526.png)

How to reproduce:
1. Open bag/profession window (so you are able to link an Item with Quality in the chat)
2. Open MacroToolKit and create a new macro
3. Write /script MacroToolkitText:Insert("") into the chat but dont send yet
4. Move the cursor between the quotation marks
5. Shift-Click the item with quality so it appears between the quotation marks
6. When you send the chat message, the linked Item appears in the macro window (looks like screenshot 2)
7. Write /2 in front of it
8. Now it looks like screenshot 1

Writing text after the linked item also looks broken.
![image](https://user-images.githubusercontent.com/5705155/206875768-d5ea0ff8-d6b4-44a8-8ffb-e07a0ba13890.png)

**Comment by Numynum** [comment]
(just as an fyi, I haven't forgotten about this issue, but sadly I haven't really had time to look into a fix for this; and it still might take a while)

**Comment by Numynum** [comment]
should be fixed next update

**Comment by chriser-** [comment]
confirmed :) thanks for the great work!
