### ISSUE TITLE
Text grayed out when using "noknown" + "known" in one []

### ISSUE THREAD

**Issue by andref243** [NumyAddon/MacroToolkit#18]
Like the title says, the whole text got gray out (see picture) when using both "noknown" and "known" in one [].

![Screenshot 2022-12-31 101443](https://user-images.githubusercontent.com/79249984/210131558-bccd87f8-2216-4063-8985-630ff1ec5c3c.jpg)

**Comment by Numynum** [comment]
Just to manage expectations, I've not forgotten about this issue, and thanks for the report :)
but since it's not breaking things (besides just looking bad), I probably won't find time to investigate and resolve this anytime soon :/

**Comment by Reakleases** [comment]
also addon complains on `nodead`
![image](https://user-images.githubusercontent.com/16504073/222556027-56b9fbf0-5179-40e4-8a0c-e2e168719188.png)

**Comment by Numynum** [comment]
the colouring issues should be fixed in next update
