### ISSUE TITLE
Wrath Classic LUA Error

### ISSUE THREAD

**Issue by Colerain** [NumyAddon/MacroToolkit#21]
Message: Interface/AddOns/MacroToolkit/MacroToolkit.lua line 154:
   attempt to index field 'LinkToButton' (a nil value)
Debug:
   [string "@Interface/AddOns/MacroToolkit/MacroToolkit.lua"]:154: eventHandler()
   [string "@Interface/AddOns/MacroToolkit/modules/initialise.lua"]:15:
      Interface/AddOns/MacroToolkit/modules/initialise.lua:15
   [string "=[C]"]: LoadAddOn()
   [string "@Interface_Wrath/FrameXML/UIParent.lua"]:385: UIParentLoadAddOn()
   [string "@Interface_Wrath/FrameXML/UIParent.lua"]:456: TradeSkillFrame_LoadUI()
   [string "@Interface_Wrath/FrameXML/UIParent.lua"]:1253:
      Interface_Wrath/FrameXML/UIParent.lua:756
   [string "=[C]"]: CastSpell()
   [string "@Interface/FrameXML/SpellBookFrame.lua"]:363: SpellButton_OnClick()
   [string "*SpellBookFrame.xml:163_OnClick"]:4:
      [string "*SpellBookFrame.xml:163_OnClick"]:1

**Comment by Numynum** [comment]
I've removed the integration with the tradeskill UI, so this shouldn't give errors anymore
