### ISSUE TITLE
It is not possible to post your profession with link in a macro

### ISSUE THREAD

**Issue by Rubyurek** [NumyAddon/MacroToolkit#24]
Every time I shift and click on my profession in makro toolkit it is only shown as a name but not as a link so the other players can click on it.

**Comment by Numynum** [comment]
![image](https://user-images.githubusercontent.com/17293527/236675655-2a8d7179-13f5-4133-8bcd-d87e1e13da7e.png)
works fine for me, if I open the macro text, Shift-Click the link, then it's posted fine in the macro, and clickable when sent through chat
