### ISSUE TITLE
Unable to open Macro Toolkit

### ISSUE THREAD

**Issue by stevedionysopolos** [NumyAddon/MacroToolkit#32]
Client Version: 1.14.3.49229
Addon Version: 2.0.4
No other addons active.
Error occurs after logging into a character.

Message: Interface\AddOns\MacroToolkit\modules\mainframe.lua:71: attempt to call method 'SetResizeBounds' (a nil value)
Time: Sat May  6 08:36:36 2023
Count: 1
Stack: Interface\AddOns\MacroToolkit\modules\mainframe.lua:71: attempt to call method 'SetResizeBounds' (a nil value)
[string "@Interface\AddOns\MacroToolkit\modules\mainframe.lua"]:71: in function `CreateMTFrame'
[string "@Interface\AddOns\MacroToolkit\MacroToolkit.lua"]:159: in function `eventHandler'
[string "@Interface\AddOns\MacroToolkit\modules\initialise.lua"]:15: in function <Interface\AddOns\MacroToolkit\modules\initialise.lua:15>

Locals: self = <table> {
 FindShortest = <function> defined @Interface\AddOns\MacroToolkit\modules\parser.lua:13
 defaults = <table> {
 }
 RunCommands = <function> defined @Interface\AddOns\MacroToolkit\modules\macrobroker.lua:81
 BindingButtonOnClick = <function> defined @Interface\AddOns\MacroToolkit\modules\bindingframe.lua:225
 IsTarget = <function> defined @Interface\AddOns\MacroToolkit\modules\parser.lua:249
 target = "/target"
 UpdateErrors = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:689
 CreateBrokerObject = <function> defined @Interface\AddOns\MacroToolkit\modules\macrobroker.lua:101
 SetBinding = <function> defined @Interface\AddOns\MacroToolkit\modules\bindingframe.lua:242
 eventHandler = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:94
 FindScript = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:448
 skinned = <table> {
 }
 UpdateIcon = <function> defined @Interface\AddOns\MacroToolkit\modules\mainframe.lua:1040
 ClearAllMacros = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:292
 FormatMacro = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:477
 Skin = <function> defined @Interface\AddOns\MacroToolkit\modules\elvskin.lua:6
 CombatMessage = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:1219
 CreateCopyFrame = <function> defined @Interface\AddOns\MacroToolkit\modules\copyframe.lua:6
 click = "/click"
 GetLastBackupDate = <function> defined @Interface\AddOns\MacroToolkit\modules\restoreframe.lua:242
 clist = <table> {
 }
 SetLastBackupDate = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:1165
 PopupButtonOnClick = <function> defined @Interface\AddOns\MacroToolkit\modules\popupframe.lua:520
 UpdateInterfaceOptions = <function> defined @Interface\AddOns\MacroToolkit\modules\options.lua:901
 UpdateIconCount = <function> defined @Interface\AddOns\MacroToolkit\modules\popupframe.lua:555
 Eval = <function> defined @Interface\AddOns\MacroToolkit\modules\macrobroker.lua:69
 SaveMacro = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:1092
 UpdateBindingFrame = <function> defined @Interface\AddOns\MacroToolkit\modules\bindingframe.lua:269
 ReceiveMacro = <function> defined @Interface\AddOns\MacroToolkit\modules\shareframe.lua:217
 CreateBuilderFrame = <function> defined @Interface\AddOns\MacroToolkit\modules\builderframe.lua:16
 Spells = <table> {
 }
 AIS = <table> {
 }
 FindComment = <function> defined @Interface\AddOns\MacroToolkit\modules\parser.lua:670
 UpdateCharLimit = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:671
 IsCast = <function> defined @Interface\AddOns\MacroToolkit\modules\parser.lua:247
 SelectTexture = <function> defined @Interface\AddOns\MacroToolkit\modules\popupframe.lua:461
 CreateSecureActionButton = <function> defined @Interface\AddOns\MacroToolkit\modules\mainframe.lua:1092
 ParseMacro = <function> defined @Interface\AddOns\MacroToolkit\modules\parser.lua:675
 L = <table> {
 }
 OptionsFrame = <unnamed> {
 }
 GetSpellorMacroIconInfo = <function> defined @Interface\AddOns\MacroToolkit\modules\popupframe.lua:429
 RGBToHex = <function> defined @Interface\AddOns\MacroToolkit\MacroToolkit.lua:321
 CreateScriptFrame = <function> defined @Interface\AddOns\MacroToolkit\modules\scriptframe.lua:6
 MACRO_ICON_FILENAMES = <table> {
 }
 S

**Comment by Numynum** [comment]
See https://github.com/NumyAddon/MacroToolkit/issues/26
classic era support will probably be back once blizzard finally updates it again
