### ISSUE TITLE
Showing correct tooltip in extended /castsequence

### ISSUE THREAD

**Issue by useronkel** [NumyAddon/MacroToolkit#33]
Hi.
Wondering why the addon doesn't shows the correct tooltip, when using an extended /castsequence running.
Any chance to fix this?

(Using a lot of macros with **very** long sequences ;-) )

**Comment by Numynum** [comment]
cast sequences are too complicated to properly 'guess' the correct tooltip for (as is done for normal /use macros)
so unfortunately this'll likely never be implemented :)
