### ISSUE TITLE
Highlight on selected macro doesn't work

### ISSUE THREAD

**Issue by zeenk** [NumyAddon/MacroToolkit#42]
I saw that this is supposed to work in the screenshots on the addon page
![2024-01-14_18-28-01](https://github.com/NumyAddon/MacroToolkit/assets/68170439/e483769c-f968-420f-a692-6c177223ac3b)

But there's no highlighting currently on live
![2024-01-14_18-30-01](https://github.com/NumyAddon/MacroToolkit/assets/68170439/0cf20cfa-d28c-4cea-9a5a-22e75b1290d6)

**Comment by Numynum** [comment]
should be fixed in next update
