### ISSUE TITLE
Unable to load the addon as of 03/02/2024

### ISSUE THREAD

**Issue by Yart-Lonewolf** [NumyAddon/MacroToolkit#43]
Hey man. I've been using this addon for years now. I can't tell you how much of a QOL improvement it has been for me. I am completely reliant on it as it's never not been there since I installed it way back when, until today!

Issue: The addon just won't function when i load in. Ontop of that it stops the regular blizzard macro UI from even being able to be accessed. I've tried clearing my WoW classic SoD cache and reinstalling the addon via CurseForge. Nothing has worked for me.

If I'm the only one having this issue I'm sorry for listing it here. But I've never had this happen with any other addon's in the past 17 years of playing this game haha. Even when an addon is out of date for me i'm able to access it, with the worst case scenario being it causing performance issues, etc.

Thanks again man for all the hard work you've put into making my WoW experience so much more enjoyable over the years

- Yart - Lonewolf

**Comment by Numynum** [comment]
Hi, for now, try install the previous version, something might've got broken with the latest one, I'll take a look

**Comment by Yart-Lonewolf** [comment]
Perfect this worked. Didn't even think of that as a solution. Will remember in the future. Thanks again!

**Comment by Numynum** [comment]
should be fixed in the next version
