### ISSUE TITLE
Out of keybind only macros.

### ISSUE THREAD

**Issue by cgsub** [NumyAddon/MacroToolkit#46]
I did not expect that but I actually run out of key bind only macro.

I actually reached 120 key bind only macros spread across my alts. 
I needed to create a new one and to my surprise the button was greyed out.

Some more slots would be welcome :)

**Comment by Numynum** [comment]
I'll see if it's easy enough to add more (or unlimited) slots 👌

**Comment by Numynum** [comment]
I didn't extensively test it, but the cap should be increased to 1000 now, good luck trying to fill those up 😜

**Comment by cgsub** [comment]
Awesome, I had a look and saw it was using G_.MAX_ACCOUNT_MACRO as a basis. 
But as it was also used to do everything for the actual account macro limit, 
I was not too confident trying to patch everything up in every file.

Thanks :)
