### ISSUE TITLE
WAR WITHIN PTR / BETA

### ISSUE THREAD

**Issue by lloskka** [NumyAddon/MacroToolkit#54]
Good Morning.

Can you do an update for beta / ptr war within?  

Now that we got "back" SABT macro text ( yes, now limited to 255 in all situations ), you should be able right?

Thanks ! have a good day.

Cheers.

**Comment by Numynum** [comment]
It's been back for a day or two, and I've been busy since 🙂 
I'm planning on getting a update done at least before prepatch, but I have quite a few addons to update, so what will be updated when, depends a bit on smoothly everything goes, and how much free time I have after my day job ^^

**Comment by Numynum** [comment]
an update should be available soon ™️, with TWW support
from limited testing, it seems to be working OK
