### ISSUE TITLE
tab autocompletion/suggestions

### ISSUE THREAD

**Issue by xenoterracide** [NumyAddon/MacroToolkit#56]
So this may be challenging/impossible. I imagine you've used IDE's which is why you added syntax highlighting. It'd be nice if you could start typing, hit tab, and either get an autocompleted (if one option, like `@play<tab>` should fill in `@player`) or a list of suggestions.

**Comment by Numynum** [comment]
I would love it (though more for spell names probably), but realistically: never gonna happen 🙂

**Comment by xenoterracide** [comment]
yeah, I would have thrown spell names and (current) inventory items into that list.
