### ISSUE TITLE
Prepatch: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))

### ISSUE THREAD

**Issue by Tovrin** [NumyAddon/MacroToolkit#58]
x bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "=[C]"]: in function `GetDefinitionInfo'
[string "@MacroToolkit/modules/parser.lua"]:44: in function <MacroToolkit/modules/parser.lua:32>
[string "@MacroToolkit/modules/parser.lua"]:60: in function <MacroToolkit/modules/parser.lua:55>
[string "@MacroToolkit/modules/parser.lua"]:314: in function <MacroToolkit/modules/parser.lua:306>
[string "@MacroToolkit/modules/parser.lua"]:836: in function `ParseMacro'
[string "@MacroToolkit/MacroToolkit.lua"]:502: in function `FormatMacro'
[string "@MacroToolkit/MacroToolkit.lua"]:851: in function `MacroFrameUpdate'
[string "@MacroToolkit/MacroToolkit.lua"]:1086: in function `MacroButtonOnClick'
[string "@MacroToolkit/MacroToolkit.lua"]:992: in function <MacroToolkit/MacroToolkit.lua:992>
[string "=[C]"]: ?

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))"

**Comment by Numynum** [comment]
Can you link your macro?
I'm not home until late next week, so it'll stay broken for a bit

**Comment by hollo6** [comment]
fixed:
parser.lua L44:
            local definitionInfo = entryInfo and entryInfo.definitionID and C_Traits.GetDefinitionInfo(entryInfo.definitionID);
