### ISSUE TITLE
ELVUI Skinning not working

### ISSUE THREAD

**Issue by Amasoful** [NumyAddon/MacroToolkit#6]
Not really sure why, but ELVUI skinning is not working for Macro Toolkit even though i have the option to reject ELVUI skinning disabled, i tried remove ELVUI S&L and Addon skins but nothing changed, can anyone help please? Below link has screenshot of macro toolkit window not skinned while the option is disabled, thanks in advance!

**Comment by Numynum** [comment]
Hi, this is a known issue 
I'm currently not planning on fixing it, since it adds a lot more complications into an already gigantic addon
so this will likely remain broken until someone creates a PR to fix it :)

**Comment by Amasoful** [comment]
Alright thanks for the feedback!
