### ISSUE TITLE
Error @MacroToolkit/modules/parser.lua

### ISSUE THREAD

**Issue by FlareStarrr** [NumyAddon/MacroToolkit#64]
```
422x bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "=[C]"]: in function `GetDefinitionInfo'
[string "@MacroToolkit/modules/parser.lua"]:44: in function <MacroToolkit/modules/parser.lua:32>
[string "@MacroToolkit/modules/parser.lua"]:60: in function <MacroToolkit/modules/parser.lua:55>
[string "@MacroToolkit/modules/parser.lua"]:314: in function <MacroToolkit/modules/parser.lua:306>
[string "@MacroToolkit/modules/parser.lua"]:836: in function `ParseMacro'
[string "@MacroToolkit/MacroToolkit.lua"]:502: in function `FormatMacro'
[string "@MacroToolkit/MacroToolkit.lua"]:851: in function `MacroFrameUpdate'
[string "@MacroToolkit/MacroToolkit.lua"]:1086: in function `MacroButtonOnClick'
[string "@MacroToolkit/MacroToolkit.lua"]:992: in function <MacroToolkit/MacroToolkit.lua:992>
[string "=[C]"]: ?

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))"
```

**Comment by Numynum** [comment]
can you add the macro you were editing, and your characters spec?

**Comment by FlareStarrr** [comment]
Hi, I'm guardian druid. But there's the same error right after /reload with the addon disabled. A disabled addon can't generate error right? Thus, I suspect it's another addon's problem but somehow attributes to MacroToolkit. I'd say it's a hassle to find out the culprit, but I'll let you know if I find it.

**Comment by FlareStarrr** [comment]
LibGroupInSpecT-1.1-1.5.0 is the culprit, it returns the error above with only this addon enabled.
The error disappears with both addons enabled after updating to LibGroupInSpecT-1.1-r105-alpha.
I'll let you know if more error occurs during the gameplay.

**Comment by Numynum** [comment]
bugsack groups "identical" errors together, which sometimes results in odd behaviour like this
in the settings you can change it so you can alt-click to clear the errors, and then it _should_ have properly blamed LibGroupInSpecT I think, just so you know in the future 🙂
