### ISSUE TITLE
Feature request, utf support

### ISSUE THREAD

**Issue by ffainy** [NumyAddon/MacroToolkit#67]
There are a lot of weird problems when using chinese spell names.

![Wow_2024_09_10_08_52_40_042](https://github.com/user-attachments/assets/112b6a3a-112f-4c5f-a509-20691dd04c4b)

![Wow_2024_09_10_08_52_24_944](https://github.com/user-attachments/assets/1ebc89a5-fbec-4393-8f4e-9c701068afeb)

![Wow_2024_09_10_08_52_08_616](https://github.com/user-attachments/assets/6d3f807e-8fcf-4a81-9ed3-8b513bf6f78b)

**Comment by Numynum** [comment]
Can you copy/paste these macros here?
no promises though, but I'll try take a look at least

**Comment by ffainy** [comment]
For example, for the condition `known`, if use spellid, it will be displayed normally, but if use spellname, it will be displayed incorrectly.
```
#showtooltip
/use [mod:alt]圣洁鸣钟
/use [known:远征打击]灰烬觉醒;十字军打击
```

**Comment by Numynum** [comment]
tried pasting it into game, but it won't show any chinese characters for me, makes this kinda impossible to reproduce or fix

**Comment by ffainy** [comment]
thanks for the reply anyway, you've made a great addon👍
