### ISSUE TITLE
Typo in Curseforge description.

### ISSUE THREAD

**Issue by Fred-IV** [NumyAddon/MacroToolkit#69]
"Some features are marked at", I think you meant "as".

Also, seems like the best, and only features I need are gone.

I wanted to be able to backup, or import/export to share between characters, but every single feature says "abandoned".

**Comment by Numynum** [comment]
Just to clarify, abandoned doesn't mean gone. It means it may work, but if it's broken, I'm unlikely to fix it unless it's trivial
see it as a disclaimer to reduce expectations 🙂

sharing between characters is something I'm considering putting back on the "actively supported" list (and yes, that also means that it works perfectly fine last time I used it)

For me personally, extended macros and syntax highlighting (and keybind-only macros perhaps) were the main reasons to offer to maintain this addon
I don't have a lot of time or motivation to work on other features, but other developers are more than welcome to pitch in 🙂 

(and I'll fix the typo, thanks 👍)
